mg/messageguru.ru/www/controllers/SiteController.php
<?php

namespace app\controllers;

use app\components\PushService;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\ProfileFiles;
use app\modules\user\models\User;
use yii\db\Expression;
use app\models\Files;

class SiteController extends Controller
{
    public $model;
    public $modelAuthor;
    public $curr;
    public $curr_author;

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
//        $push = new PushService();
//        $push->sendPushNewSubscriber(Yii::$app->user->id, 5);
//        die();
//        //$push->testPush(5, 174);
//        die('dgsdfgfdsg');


        $this->model = ProfileFiles::find()->where(["status" => 1])->limit(6)->orderBy(['created_at' => SORT_DESC])->all();
        
        $this->modelAuthor = User::find()->andWhere(["status" => User::STATUS_ACTIVE])->orderBy('rating')->limit(6)->all();
        return $this->render('index', [
            'messages' => $this->model,
            'modelAuthor' => $this->modelAuthor,
            'curr' => 3,
            'curr_author' => 3
        ]);
    }

    /*
     * фильтры для през на главной
     */

    public function actionFilterToday()
    {
        $this->model = ProfileFiles::find()->where('DATE(`created_at`) = CURDATE()')->andWhere(["status" => 1])->limit(6)->orderBy(['created_at' => SORT_DESC])->all();
        return $this->render('index', ['modelAuthor' => [], 'messages' => $this->model, 'curr' => 1]);
    }

    public function actionFilterMonth()
    {
        $this->model = ProfileFiles::find()->where('DATE(`created_at`) > DATE_SUB(CURRENT_DATE, INTERVAL 1 MONTH)')->andWhere(["status" => 1])->limit(6)->orderBy(['created_at' => SORT_DESC])->all();
        return $this->render('index', ['modelAuthor' => [], 'messages' => $this->model, 'curr' => 2]);
    }

    public function actionFilterAll()
    {
        $this->model = ProfileFiles::find()->where(["status" => 1])->limit(6)->orderBy(['created_at' => SORT_DESC])->all();
        return $this->render('index', ['modelAuthor' => [], 'messages' => $this->model, 'curr' => 3]);
    }

    public function actionFilterRand()
    {
        //$this->model = ProfileFiles::find()->where(["status" => 1])->orderBy(new Expression('rand()'))->limit(6)->orderBy(['created_at' => SORT_DESC])->all();

        $this->model = Files::find()
            ->where(["status" => 1])
            ->orderBy(new Expression('rand()'))
            ->limit(6)
            ->all();

        return $this->render('index', ['modelAuthor' => [], 'messages' => $this->model, 'curr' => 3]);
    }

    /*
 * фильтры авторов на главной
 */

    public function actionFilterAuthorToday()
    {
        $this->modelAuthor = User::find()->where('DATE(`created_at`) = CURDATE()')->orderBy('rating')->andWhere(["status" => User::STATUS_ACTIVE])->limit(6)->all();
        return $this->render('index', ['messages' => [], 'modelAuthor' => $this->modelAuthor, 'curr_author' => 1]);
    }

    public function actionFilterAuthorMonth()
    {
        $this->modelAuthor = User::find()->where('DATE(`created_at`) = DATE_SUB(CURRENT_DATE, INTERVAL 1 MONTH)')->andWhere(["status" => User::STATUS_ACTIVE])->orderBy('rating')->limit(6)->all();
        return $this->render('index', ['messages' => [], 'modelAuthor' => $this->modelAuthor, 'curr_author' => 2]);
    }

    public function actionFilterAuthorAll()
    {
        $this->modelAuthor = User::find()->limit(6)->orderBy('rating')->andWhere(["status" => User::STATUS_ACTIVE])->all();
        return $this->render('index', ['messages' => [], 'modelAuthor' => $this->modelAuthor, 'curr_author' => 3]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /*
     * статичные страницы
     */
    public function actionEvents(){
        return $this->render('events');
    }

    public function actionEducation(){
        return $this->render('education');
    }

    public function actionBusiness(){
        return $this->render('business');
    }
}

mg/messageguru.ru/www/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'О проекте';
//$this->params['breadcrumbs'][] = $this->title;
?>
<?php $this->beginContent('@app/views/layouts/layout_main.php'); ?>
<div class="noise_light bg_sub overflow bordered">
    <div class="wrapper">
        <h1><?= Html::encode($this->title) ?></h1>

        <p>Проект MessageGuru создан для обмена идеями и сообщениями. Любая презентация, выступление или доклад всегда
            несут
            для аудитории «сообщение», которое объединяет все сказанное спикером.</p>
        <p>Участники проекта MG могут регистрироваться под своими именами и рассказывать профессиональному сообществу о
            своих идеях, презентовать проекты, публиковать выступления.</p>
        <p>Мы надеемся, что общение на площадке будет конструктивным и благодаря фильтру со стороны участников поможет
            естественным образом отсеивать наиболее интересные идеи, угадывать и предвещать новые тренды, помогать
            разбирать
            уже случившиеся проекты и делиться опытом.</p>
        <p>Удачи в создании своих сообщений!</p>

    </div>
</div>
</div>
<?php $this->endContent(); ?>

mg/messageguru.ru/www/views/site/business.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Business';
$this->params['breadcrumbs'][] = $this->title;
?>
<?php $this->beginContent('@app/views/layouts/layout_main.php'); ?>

    <div class="site-about">
        <h1><?= Html::encode($this->title) ?></h1>

        <p>
            This is the page. You may modify the following file to customize its content:
        </p>

        <code><?= __FILE__ ?></code>
    </div>
<?php $this->endContent(); ?>

mg/messageguru.ru/www/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

mg/messageguru.ru/www/views/site/education.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Education';
$this->params['breadcrumbs'][] = $this->title;
?>
<?php $this->beginContent('@app/views/layouts/layout_main.php'); ?>

<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>
<?php $this->endContent(); ?>

mg/messageguru.ru/www/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = $name;
?>

<?php Html::encode($this->title) ?>

<?php nl2br(Html::encode($message)) ?>
<?php $this->beginContent('@app/views/layouts/layout_no_header.php'); ?>


    <div class="register_container login_container flex_container">
        <div class="outline">

            <div class="inline_logo">Message<span>GURU</span></div>

            <h1 class="error_page_numbers color_primary"><?= Html::encode($exception->statusCode) ?></h1>
            <?php if($exception->statusCode == 404)
            {
                echo '<p>К сожалению, запрашиваемая страница не найдена.</p>';
            } else {
                echo Html::encode(preg_replace("/[.]+$/", "", trim($exception->getMessage())));
            }
            ?>


            <?= Html::a('Вернуться на главную!', Url::home(), ['class' => 'btn bg_primary']) ?>

        </div>
    </div>


<?php $this->endContent(); ?>

mg/messageguru.ru/www/views/site/events.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Events';
$this->params['breadcrumbs'][] = $this->title;
?>
<?php $this->beginContent('@app/views/layouts/layout_main.php'); ?>

    <div class="site-about">
        <h1><?= Html::encode($this->title) ?></h1>

        <p>
            This is the page. You may modify the following file to customize its content:
        </p>

        <code><?= __FILE__ ?></code>
    </div>
<?php $this->endContent(); ?>

mg/messageguru.ru/www/views/site/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Pjax;
use app\assets\AppAsset;
use app\modules\user\models\User;
use \app\models\Files;
use \app\components\widgets\SearchWidget;
use app\components\widgets\LikesWidget;

AppAsset::register($this);
$assetsUrl = AppAsset::getAssetsUrl();

/* @var $this yii\web\View */

$this->title = 'Сервис обмена презентациями';
?>

<?php $this->beginContent('@app/views/layouts/layout_main.php'); ?>

    <div class="search">
        <div class="wrapper">
            <?= SearchWidget::widget() ?>
        </div>
        <div class="search_mask transition"></div>
    </div>

    <div class="noise_light bg_sub overflow bordered">
        <div class="wrapper">
            <?php Pjax::begin(); ?>
            <div class="preheader">
                <h2 class="left"><span class="color_primary">Лучшие:</span></h2>
                <div class="filters left">
                    <?= Html::a("За сегодня", ['site/filter-today'], ['class' => 'filter ' . (($curr == 1) ? 'active_filter' : '')]) ?>
                    <?= Html::a("За месяц", ['site/filter-month'], ['class' => 'filter ' . (($curr == 2) ? 'active_filter' : '')]) ?>
                    <?= Html::a("За все время", ['site/filter-all'], ['class' => 'filter ' . (($curr == 3) ? 'active_filter' : '')]) ?>

                </div>

                <?= Html::a("Рулетка | Cлучайные 6", ['site/filter-rand'], ['class' => 'btn bg_primary transition get_random left']) ?>

                <div class="gun color_primary left fa fa-refresh"></div>
            </div>

            <div class="col col_l left ">
                <div class="messages_container overflow">
                    <?php foreach ($messages AS $file) {
                        echo \app\components\widgets\RenderFileItemWidget::widget(['model' => $file]);
                    } ?>
                </div>
            </div>
            <?php Pjax::end(); ?>
            <div class="col col_s right recommendations">
                <h2 class="bold_title">Рекомендации <span class="color_primary">MG для Вас:</span></h2>
                <?= \app\components\widgets\RecommendBar::widget() ?>


                <div class="tags">
                    <h2 class="bold_title">Популярные теги:</h2>
                    <?= \app\components\widgets\TagsBar::widget() ?>
                </div>
            </div>
            <div class="load_more">
                <span class="load_more_left left"></span>
                <div class="load_selector left">
                    <div></div>
                    <?= Html::a('Показать больше', Url::to(['/presentation']), ['class' => 'color_primary', 'data-pjax' => 0]) ?>
                </div>
                <span class="load_more_right left contain_right"></span>
            </div>
        </div>
    </div>

    <div class=" noise_light overflow">
        <div class="wrapper">
            <?php Pjax::begin(); ?>
            <div class="col col_l left autor_block">
                <div class="preheader">
                    <h2 class="left"><span class="color_primary">Топ</span> Авторов:</h2>
                    <div class="filters left">
                        <?= Html::a("За сегодня", ['site/filter-author-today'], ['class' => 'filter ' . (($curr_author == 1) ? 'active_filter' : '')]) ?>
                        <?= Html::a("За месяц", ['site/filter-author-month'], ['class' => 'filter ' . (($curr_author == 2) ? 'active_filter' : '')]) ?>
                        <?= Html::a("За все время", ['site/filter-author-all'], ['class' => 'filter ' . (($curr_author == 3) ? 'active_filter' : '')]) ?>

                    </div>
                </div>

                <div class="author_container overflow">
                    <?php
                    /** @var \app\modules\user\models\User $user */
                    foreach ($modelAuthor AS $user) { ?>
                        <div class="author">
                            <?= Html::a('<div class="author_photo" style="background-image: url(' . $user->getAvatarUrl() . ')" ></div>', Url::to(['/author/' . $user->id]), ['data-pjax' => 0]) ?>
                            <div class="bg_primary pq_counter"><?= $user->getCurrentUserTextLevel() ?></div>
                            <h3 class="author_name color_primary"><?= Html::a($user->first_name . ' ' . $user->last_name, Url::to(['/author/' . $user->id]), ['data-pjax' => 0]) ?></h3>
                        </div>
                    <?php } ?>
                </div>


                <div class="load_more">
                    <span class="load_more_left left"></span>
                    <div class="load_selector left">
                        <div></div>
                        <?= Html::a('Показать больше', Url::to(['/authors']), ['class' => 'color_primary', 'data-pjax' => 0]) ?>
                    </div>
                    <span class="load_more_right left"></span>
                </div>

            </div>
            <?php Pjax::end(); ?>
            <div class="col col_s right promo">
                <div class="block fst_adv" style="visibility: hidden">
                    Рекламный блок
                </div>
                <div class="block scn_adv bg_secondary" style="visibility: hidden"></div>
            </div>

        </div>

    </div>


<?php $this->endContent(); ?>

mg/messageguru.ru/www/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>


    <?php
    if (Yii::$app->getSession()->hasFlash('error')) {
        echo '<div class="alert alert-danger">'.Yii::$app->getSession()->getFlash('error').'</div>';
    }
    ?>
    <p class="lead">Do you already have an account on one of these sites? Click the logo to log in with it here:</p>
    <?php echo \nodge\eauth\Widget::widget(array('action' => 'site/login')); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>