mg/messageguru.ru/www/controllers/PresentationController.php
<?php
/**
 * Created by PhpStorm.
 * User: manchetten
 * Date: 21.03.17
 * Time: 22:51
 */

namespace app\controllers;

use app\models\CategoriesDict;
use app\models\Files;
use app\models\forms\AddPresentationForm;
use app\modules\user\models\User;
use Yii;
use yii\filters\AccessControl;
use app\components\BaseController;
use yii\web\NotFoundHttpException;
use yii\data\ActiveDataProvider;
use app\modules\user\models\UploadForm;
use yii\web\UploadedFile;
use yii\web\Response;
use yii\widgets\ActiveForm;
use yii\db\Expression;
use yii\helpers\Inflector;
use yii\helpers\Url;
use yii\helpers\Html;
use app\components\PushService;

/**
 * Контроллер для отображения презентаций
 * Class PresenatationController
 * @package app\controllers
 */
class PresentationController extends BaseController
{
    /**
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionIndex()
    {
        //Если указана категория - фильтруем
        $cat = Yii::$app->request->get('cat', '');

        if (!empty($cat) && in_array($cat, array_keys(CategoriesDict::getCatsList(true))))
            $q = Files::find()->where(["status" => 1, 'cat_id' => CategoriesDict::getCatIdByAlias($cat)]);
        else
            $q = Files::find()->where(["status" => 1]);

        //Иначе - список всех презентаций
        $filesProvider = new ActiveDataProvider([
            'query' => $q,
            'pagination' => [
                'pageSize' => 6,
            ],
            'sort' => [
                'defaultOrder' => ['created_at' => SORT_DESC]
            ]
        ]);
        if (!empty($filesProvider)) {
            return $this->render('files_list', ['filesProvider' => $filesProvider, 'curr' => 1]);
        } else throw new NotFoundHttpException();
    }

    //ищем messages по переданому тегу
    public function actionTags()
    {
        $tag_alias = Yii::$app->request->get('tag', '');

        $filesProvider = new ActiveDataProvider([
            'query' => Files::find()->joinWith('filesTags')->andFilterWhere(['alias' => $tag_alias]),
            'pagination' => [
                'pageSize' => 6,
            ],
            'sort' => [
                'defaultOrder' => ['created_at' => SORT_DESC]
            ]
        ]);
        if (!empty($filesProvider)) {
            return $this->render('files_list', ['filesProvider' => $filesProvider, 'curr' => 1]);
        } else throw new NotFoundHttpException();
    }

    public function actionAuthor()
    {
        $author_id = Yii::$app->request->get('author', '');

        $model = User::find()->joinWith('achievements')->where(['login' => $author_id])->with("files")->one();

        //Есть автор - рендерим страницу файлов автора
        if (!empty($author_id)) {
            $usersProvider = new ActiveDataProvider([
                'query' => Files::find()->where(['user_id' => $author_id])->andWhere(["status" => 1]),

                'pagination' => [
                    'pageSize' => 6,
                ],
                'sort' => [
                    'defaultOrder' => ['created_at' => SORT_DESC]
                ]
            ]);
        }
        if (!empty($usersProvider)) {
            return $this->render('files_list_author', [
                'usersProvider' => $usersProvider,
                'model' => $model
            ]);
        } else throw new NotFoundHttpException();
    }

    public function sendMail($mail)
    {
        if (!empty(Yii::$app->getUser()->id)) {

            $id = Yii::$app->request->get('file', '');

            if (!empty($id)) {
                $model = Files::findOne($id);
                $images = $model->getImages($model->id);
                $img_path = Yii::getAlias('@app/modules/user/assets/img/mail/');

                Yii::$app->mailer->compose('@app/views/presentation/mail/share', [
                    'model' => $model,
                    'images' => $images,
                    'bg' => $img_path . 'bg.png',
                    'body' => $img_path . 'body.png',
                    'footer' => $img_path . 'footer.png',
                    'head' => $img_path . 'head.png',
                ])
                    ->setFrom(Yii::$app->params['mailFrom'])
                    ->setTo($mail)
                    ->setSubject('Ваш друг  ' . User::getFullname(Yii::$app->getUser()->id) . '  поделился с вами презентацией')
                    ->send();
            }
        }
    }

    /**
     * Экшн для просмотра конкретного файла\презы
     */
    public function actionView()
    {
        if (!empty(Yii::$app->request->post()) && !empty(Yii::$app->request->post()['Files']['mail'])) {
            $this->sendMail(Yii::$app->request->post()['Files']['mail']);
        }

        $id = Yii::$app->request->get('file', '');

        if (!empty($id)) {
            $model = Files::find()
                ->joinWith('filesTags')
                ->where([
                    'files.id' => $id,
                    'files.status' => Files::STATUS_ON
                ])
                ->one();

            if (!empty($model)) {

                Yii::$app->view->registerMetaTag(['property' => 'og:title', 'content' => $model->title]);
                Yii::$app->view->registerMetaTag(['property' => 'og:url', 'content' => Url::to(['/pres/' . $model->id], true)]);
                Yii::$app->view->registerMetaTag(['property' => 'og:image', 'content' => $model->getImageUrl()]);
                Yii::$app->view->registerMetaTag(['property' => 'og:description', 'content' => $model->desc]);

                $user = User::find()->joinWith('achievements')->where(['user.id' => $model->user_id])->with("files")->one();

                $model->updateCounters(['views' => 1]);

                return $this->render('file_view', ['model' => $model, 'user' => $user]);

            } else throw new NotFoundHttpException();
        } else throw new NotFoundHttpException();
    }

    public function actionAdd()
    {
        $model = new Files();

        $load = $model->load(Yii::$app->request->post());


        if (!empty(Yii::$app->user->id)) {
            $model->user_id = Yii::$app->user->id;
        } else {
            return $this->redirect(['user/do/login']);
        }

        $model->loadStep = Files::LOAD_STEP_FIRST;

        if ($load) {

            if ($model->type == Files::TYPE_PRESENTATION) {

                $model->presFile = UploadedFile::getInstance($model, 'presFile');
                $model->imageFile = UploadedFile::getInstance($model, 'imageFile');


                if (!empty($model->presFile)) {

                    if ($model->validate()) {

                        if ($filename = $model->uploadFile()) {
                            $model->name = $filename;
//                        $model->title = "files step 1";
                        }

//                    if ($imagename = $model->uploadImage())
//                        $model->image = $imagename;


                        if ($model->save(false)) {

                            //$model->saveTags();

                            $model->createTempFile();

                            Yii::$app->getSession()->setFlash('success', 'Ваша презентация успешно загружена! Заполните описание презентации, пока мы преобразовываем ее к нужному формату');

                            return $this->redirect(['presentation/upload-step-two/' . $model->id]);
                        } else {
                            Yii::$app->getSession()->setFlash('error', 'Произошла ошибка при загрузке');

                            return $this->redirect(['add']);
                        }
                    } else {
//                    print_r($model->getErrors());
//                    die();
                        Yii::$app->getSession()->setFlash('error', 'Произошла ошибка при загрузке');

                        //return $this->redirect(['add']);
                        return $this->render('add_presentation', [
                            'model' => $model
                        ]);
                    }

                }
            } else {

                $model->title = "new video";

                if ($model->validate()) {
                    preg_match("/^(?:http(?:s)?:\/\/)?(?:www\.)?(?:m\.)?(?:youtu\.be\/|youtube\.com\/(?:(?:watch)?\?(?:.*&)?v(?:i)?=|(?:embed|v|vi|user)\/))([^\?&\"'>]+)/", $model->name, $matches);

                    if (!empty($matches[1])) {
                        $model->name = $matches[1];
                    }

                    if ($model->save()) {
                        //$model->saveTags();
                        Yii::$app->getSession()->setFlash('success', 'Ваша презентация успешно загружена! Заполните описание презентации, пока мы преобразовываем ее к нужному формату');

                        return $this->redirect(['presentation/video-step-two/' . $model->id]);
                    } else {
                        Yii::$app->getSession()->setFlash('error', 'Произошла ошибка при загрузке');
                    }
                } else {
                    print_r($model->getErrors());
                    die();
                }
            }
        } else {
            return $this->render('add_presentation', [
                'model' => $model
            ]);

        }
    }

    /**
     * Экшен второго шага загрузки видео
     * @return array|string|Response
     */
    public function actionVideoStepTwo($model_id)
    {
        if (!empty($model_id)) {
            $model = Files::findOne($model_id);

            $model->loadStep = Files::LOAD_STEP_SECOND;
            $model->image = 'https://i.ytimg.com/vi/' . $model->name . '/hqdefault.jpg';

            if (Yii::$app->request->post()) {
                $load = $model->load(Yii::$app->request->post());

                $model->slug = Inflector::slug($model->title);
                $model->status = 1;

                if ($model->validate()) {

                    if ($model->save()) {

mg/messageguru.ru/www/controllers/SiteController.php
<?php

namespace app\controllers;

use app\components\PushService;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\ProfileFiles;
use app\modules\user\models\User;
use yii\db\Expression;
use app\models\Files;

class SiteController extends Controller
{
    public $model;
    public $modelAuthor;
    public $curr;
    public $curr_author;

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
//        $push = new PushService();
//        $push->sendPushNewSubscriber(Yii::$app->user->id, 5);
//        die();
//        //$push->testPush(5, 174);
//        die('dgsdfgfdsg');


        $this->model = ProfileFiles::find()->where(["status" => 1])->limit(6)->orderBy(['created_at' => SORT_DESC])->all();
        
        $this->modelAuthor = User::find()->andWhere(["status" => User::STATUS_ACTIVE])->orderBy('rating')->limit(6)->all();
        return $this->render('index', [
            'messages' => $this->model,
            'modelAuthor' => $this->modelAuthor,
            'curr' => 3,
            'curr_author' => 3
        ]);
    }

    /*
     * фильтры для през на главной
     */

    public function actionFilterToday()
    {
        $this->model = ProfileFiles::find()->where('DATE(`created_at`) = CURDATE()')->andWhere(["status" => 1])->limit(6)->orderBy(['created_at' => SORT_DESC])->all();
        return $this->render('index', ['modelAuthor' => [], 'messages' => $this->model, 'curr' => 1]);
    }

    public function actionFilterMonth()
    {
        $this->model = ProfileFiles::find()->where('DATE(`created_at`) > DATE_SUB(CURRENT_DATE, INTERVAL 1 MONTH)')->andWhere(["status" => 1])->limit(6)->orderBy(['created_at' => SORT_DESC])->all();
        return $this->render('index', ['modelAuthor' => [], 'messages' => $this->model, 'curr' => 2]);
    }

    public function actionFilterAll()
    {
        $this->model = ProfileFiles::find()->where(["status" => 1])->limit(6)->orderBy(['created_at' => SORT_DESC])->all();
        return $this->render('index', ['modelAuthor' => [], 'messages' => $this->model, 'curr' => 3]);
    }

    public function actionFilterRand()
    {
        //$this->model = ProfileFiles::find()->where(["status" => 1])->orderBy(new Expression('rand()'))->limit(6)->orderBy(['created_at' => SORT_DESC])->all();

        $this->model = Files::find()
            ->where(["status" => 1])
            ->orderBy(new Expression('rand()'))
            ->limit(6)
            ->all();

        return $this->render('index', ['modelAuthor' => [], 'messages' => $this->model, 'curr' => 3]);
    }

    /*
 * фильтры авторов на главной
 */

    public function actionFilterAuthorToday()
    {
        $this->modelAuthor = User::find()->where('DATE(`created_at`) = CURDATE()')->orderBy('rating')->andWhere(["status" => User::STATUS_ACTIVE])->limit(6)->all();
        return $this->render('index', ['messages' => [], 'modelAuthor' => $this->modelAuthor, 'curr_author' => 1]);
    }

    public function actionFilterAuthorMonth()
    {
        $this->modelAuthor = User::find()->where('DATE(`created_at`) = DATE_SUB(CURRENT_DATE, INTERVAL 1 MONTH)')->andWhere(["status" => User::STATUS_ACTIVE])->orderBy('rating')->limit(6)->all();
        return $this->render('index', ['messages' => [], 'modelAuthor' => $this->modelAuthor, 'curr_author' => 2]);
    }

    public function actionFilterAuthorAll()
    {
        $this->modelAuthor = User::find()->limit(6)->orderBy('rating')->andWhere(["status" => User::STATUS_ACTIVE])->all();
        return $this->render('index', ['messages' => [], 'modelAuthor' => $this->modelAuthor, 'curr_author' => 3]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /*
     * статичные страницы
     */
    public function actionEvents(){
        return $this->render('events');
    }

    public function actionEducation(){
        return $this->render('education');
    }

    public function actionBusiness(){
        return $this->render('business');
    }
}

mg/messageguru.ru/www/views/presentation/add_presentation.php
<?php
/**
 * Created by PhpStorm.
 * User: manchetten
 * Date: 28.03.17
 * Time: 10:29
 */


use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use app\models\Tags;
use app\models\Files;
use kartik\file\FileInput;
use yii\helpers\Url;
use app\modules\user\models\User;

$this->title = "Добавить презентацию";

$script = <<< JS
    $(document).ready(function(){
        $("#files-presfile").on("change", function() {
          $("#w0").submit();
        })
    })
JS;
//маркер конца строки, обязательно сразу, без пробелов и табуляции
$this->registerJs($script, yii\web\View::POS_READY);

?>

<div class="bg_sub noise_light">
    <?php $this->beginContent('@app/views/layouts/layout_main.php'); ?>
    <div class="wrapper_addform">




        <h1 class="color_primary">Шаг 1:</h1>
        <div class="message_block_underline"></div>

        <ul class="nav nav-tabs">
          <li class="active"><a data-toggle="tab" href="#pres">Презентация</a></li>
          <li><a data-toggle="tab" href="#video">Видео</a></li>
        </ul>

        <div class="tab-content">

            <div id="pres" class="tab-pane fade in active">
                <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>
                <div class="block overflow add_message_block add_message_zone  noise_light">
                    <i class="fa color_secondary icon_upload fa-cloud-upload" aria-hidden="true"></i>
                    <?= $form->field($model, 'type')->hiddenInput(['value' => Files::TYPE_PRESENTATION])->label(false) ?>
                    <div class="file_upload">
                        <button type="button" class="btn bg_primary">Выбрать файл!</button>
                        <?= $form->field($model, 'presFile')->fileInput(['accept'=>'application/pdf,application/vnd.oasis.opendocument.presentation,application/vnd.ms-powerpoint,application/vnd.openxmlformats-officedocument.presentationml.presentation']) ?>
                    </div>
                </div>
                <?php ActiveForm::end(); ?>
            </div>

            <div id="video" class="tab-pane fade">
                <?php $form = ActiveForm::begin(); ?>
                <div class="block overflow add_message_block add_message_zone  noise_light">
                    <i class="fa color_secondary icon_upload fa-youtube-square" aria-hidden="true"></i>
                    <div class="video_form">
                        <?= $form->field($model, 'type')->hiddenInput(['value' => Files::TYPE_YOUTUBE])->label(false) ?>
                        <?= $form->field($model, 'name')->label(false)->textInput(
                            [
                                'placeholder' => 'Ссылка на видео с youtube...',
                            ]
                        ) ?>
                        <input type="submit" class="btn bg_primary" value ="Далее!">
                    </div>
                </div>
                <?php ActiveForm::end(); ?>
            </div>

        </div>
    </div>

    <?php $this->endContent(); ?>
</div>

mg/messageguru.ru/www/views/presentation/add_presentation_step_2.php
<?php
/**
 * Created by PhpStorm.
 * User: manchetten
 * Date: 28.03.17
 * Time: 10:29
 */


use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use app\models\Tags;
use app\models\Files;
use kartik\file\FileInput;
use yii\helpers\Url;
use app\modules\user\models\User;
use yii\widgets\Pjax;

$this->title = "Добавить презентацию - Шаг 2";

$get_images_url = Url::to(['json-gate/get-images', 'id' => $model->id]);
$check_url = Url::to(['json-gate/get-count', 'id' => $model->id]);
$id = $model->id;

$script = <<< JS
var baseUrl = '$check_url';
var countPages;
var currCnt = 0;
var parse = false;

var model_id = '$id';
var isCheck = true;

$(document).ready(function() {
    $("#files-title").val("");
    
    $(document).on("click", '.presentation_slide', function(event) { 
        //console.log($(this));
        $("#files-image").val($(this).attr("rel"));
    });
    
    //Hover select slide
    $('.presentation_prew_item').hover(function () {
            $(this).append('<div class="take_main">Сделать основным слайдом!</div>');
            $(this).find('.take_main').fadeIn(300);
    })
    $('.presentation_prew_item').mouseleave(function () {
            $(this).find('.take_main').remove();
    })
        
    function slideSelector() {
        //Select main slide
        $('.presentation_prew_item').click(function () {
            $('.presentation_prew_item').removeClass('slide_selected');
            $(this).addClass('slide_selected');
            $('.slide_check').remove();
            $(this).append('<div class="slide_check bg_primary"><i class="fa fa-check" aria-hidden="true"></i></div>');
        })
    }
    
    function checkCount() {
        if(isCheck) {
          $.ajax({
                url: '$check_url'
            }).done(function(data) {
                var old_pages_count = window.localStorage.getItem(model_id + 'loaded_pages');
                if(!old_pages_count)
                    window.localStorage.setItem(model_id + 'loaded_pages', data.data.pages_loaded);
                
                console.log('Old pages: ', old_pages_count);
               
                if(old_pages_count < data.data.pages_loaded) {
                    if(data.data.need_conversion && data.data.is_converted == 0) {
                      $('.progress-bar').text('Преобразуем презентацию в правильный формат');
                    } else {
                       $('.progress-bar').text("Загружено " + data.data.pages_loaded + " слайдов из " + data.data.pages_total);
                       //console.log(currCnt*100/countPages +"px");
                       $('.progress-bar').css("width", (data.data.pages_loaded*100/data.data.pages_total) +"%");
                       window.localStorage.setItem(model_id + 'loaded_pages', data.data.pages_loaded);
                       getImages(data.data);
                    }
                } else {
                    $('.progress-bar').text('Преобразуем презентацию в правильный формат');
                }
                    
                if(old_pages_count == data.data.pages_total && !data.data.need_conversion) {
                    isCheck = false;
                    window.localStorage.removeItem(model_id + 'loaded_pages');
                    $('.progress-bar').text('Презентация успешно преобразована! Выберите главную картинку презентации');
                }
               
            });
        }
    }
    
    function getImages(stat) {
      $.ajax({
            url: '$get_images_url'
        }).done(function(data) {
            var imageCollection = $('.presentation_prew_item');
            var template = '';
            currCnt = imageCollection.length;
            
            for(i = imageCollection.length-1; i < Object.keys(data.data).length; i++){
                if(data.data[i] && data.data[i] !='undefined')
                    template += '<div class="presentation_prew_item"><div class="presentation_slide" rel="'+data.data[i]+'" style="background-image: url('+data.data[i]+')"></div><span>Слайд #'+(i+1)+'</span></div>';
            }
            
            if(template && typeof template != 'undefined')
                imageCollection.last().after(template);            
            
            slideSelector();
            
            // if(first){
            //     $('.slide_check').hide();
            //     $('.presentation_prew_item').eq(1).addClass('slide_selected');
            // }
        });
    }
    
    setInterval(function(){
         checkCount();
    }, 3000);
});
   
JS;
$this->registerJs($script, yii\web\View::POS_END);/*    setInterval(function(){
    $("#refreshButton").click();
}, 3000);*/
?>
<div class="bg_sub noise_light">
    <?php $this->beginContent('@app/views/layouts/layout_main.php'); ?>


    <div class="wrapper_addform wrapper_addform_step_two">
        <h1 class="color_primary">Шаг 2:</h1>
        <div class="message_block_underline"></div>


        <div class="col col_l left">
            <div class="progress">
                <div class="progress-bar progress-bar-striped active bg_primary" role="progressbar"
                     aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width:0%">

                </div>
            </div>
            <div class="block presentation_prew_zone">
                <div class="presentation_prew_item" style="display: none"></div>
            </div>
            <div class="line_hide"></div>
        </div>

        <div class="col col_s right">
            <div class="block">
                <?php $form = ActiveForm::begin([
                    'enableAjaxValidation' => true,
                    'enableClientValidation' => false,
                    'validateOnChange' => true,
                ]); ?>
                <div class="form-group field-registrationform-email required add_message_form">
                    <?= $form->field($model, 'type')->hiddenInput(['value' => Files::TYPE_PRESENTATION])->label(false) ?>
                    <?= $form->field($model, 'image')->hiddenInput()->label(false) ?>
                    <?= $form->field($model, 'title')->label(false)->textInput(
                        [
                            'placeholder' => 'Название презентации...',
                            'class' => 'form-control',
                            'aria-required' => "true"
                        ]
                    ) ?>


                    <?= $form->field($model, 'cat_id')->label(false)->dropDownList(
                        \app\models\CategoriesDict::getCatsList(),
                        [
                            'placeholder' => 'Категория',
                            'class' => 'form-control',
                            'aria-required' => "true"
                        ]
                    ); ?>

                    <!--  <?= $form->field($model, 'type')->label(false)->dropDownList(
                        app\models\Files::getTypesList(),
                        array(
                            'placeholder' => 'Тип презентации...',
                            'class' => 'form-control',
                            'aria-required' => "true"
                        )
                    ); ?> -->
                    <?= $form->field($model, 'desc')->label(false)->textarea(
                        [
                            'placeholder' => 'Краткое описание...',
                            'class' => 'form-control',
                            'aria-required' => "true"
                        ]
                    ) ?>

                    <?= $form->field($model, 'tags')->widget(Select2::classname(), [
                        'data' => Tags::getTagsList(),
                        'showToggleAll' => false,
                        'options' => ['placeholder' => 'Выберите теги ...', 'multiple' => true],
                        'pluginOptions' => [
                            'tags' => true,
                            'tokenSeparators' => [',', ' '],
                            'maximumInputLength' => 30
                        ],
                    ])->label(''); ?>
                    <?= Html::submitButton('Сохранить', ['class' => 'btn bg_primary transition']) ?>
                </div>
                <?php ActiveForm::end(); ?>
            </div>
        </div>

    </div>
    <div class="clear"></div>


    <?php $this->endContent(); ?>

</div>

mg/messageguru.ru/www/views/presentation/files_list.php
<?php
/**
 * Created by PhpStorm.
 * User: marduk
 * Date: 25.03.17
 * Time: 11:10
 */

/* @var \yii\data\ActiveDataProvider $filesProvider */


use yii\widgets\ListView;
use app\modules\user\models\User;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Pjax;
use \app\components\widgets\SearchWidget; 

$this->title = 'Все презентации';
?>

<?php $this->beginContent('@app/views/layouts/layout_main.php'); ?>


<div class="search">
    <div class="wrapper">
        <?= SearchWidget::widget() ?>
    </div>
    <div class="search_mask transition"></div>
</div>

<div class="noise_light overflow bordered">
    <div class="wrapper">
        <h1 style="display: none"><?= $this->title ?></h1>
        <?php Pjax::begin(); ?>
        <div class="preheader">
            <h2 class="left"><span class="color_primary"> </span> Messages:</h2>
            <div class="filters left">
                <?= Html::a("Все", ['presentation/index'], ['class' => 'filter ' . (($curr == 1) ? 'active_filter' : '')]) ?>
                <?= Html::a("Новые", ['presentation/filter-new'], ['class' => 'filter ' . (($curr == 2) ? 'active_filter' : '')]) ?>
                <?= Html::a("По читаемости", ['presentation/filter-popular'], ['class' => 'filter ' . (($curr == 3) ? 'active_filter' : '')]) ?>
            </div>


            <?= Html::a("Рулетка | Cлучайные 6", ['presentation/filter-rand'], ['class' => 'btn bg_primary transition get_random left']) ?>

            <div class="gun left fa fa-refresh"></div>
        </div>

        <div class="col col_l left autor_block">
            <div class="messages_container overflow">
                <?= ListView::widget([
                    'dataProvider' => $filesProvider,
                    'options' => [
                        'tag' => 'div'
                    ],
                    'layout' => "{items}\n <div class='clear'> {pager}</div> ",
                    'itemView' => function ($model, $key, $index, $widget) {
                        return $this->render('list_item',['model' => $model]);

                        // or just do some echo
                        // return $model->title . ' posted by ' . $model->author;
                    },
                    'itemOptions' => [
                        'tag' => false,
                    ],
                    'pager' => [
                        'maxButtonCount' => 5,
                        'options' => [
                            'class' => 'color_primary pagination',
                        ],

                        'activePageCssClass' => 'bg_primary active',
                    ],
                ]);
                ?>
            </div>
        </div>
        <div class="col col_s right recommendations">
            <h2 class="bold_title">Рекомендации <span class="color_primary">MG для Вас:</span></h2>
            <?= \app\components\widgets\RecommendBar::widget() ?>
            <div class="tags">
                <h2 class="bold_title">Популярные теги:</h2>

                <?= \app\components\widgets\TagsBar::widget() ?>
            </div>
        </div>
        <?php Pjax::end(); ?>
    </div>
</div>






<?php $this->endContent(); ?>

mg/messageguru.ru/www/views/presentation/list_item.php
<?php
// _list_item.php

/* @var \app\models\Files $model */
use yii\helpers\Html;
use yii\helpers\Url;
use app\modules\user\models\User;
use app\components\widgets\LikesWidget;

echo \app\components\widgets\RenderFileItemWidget::widget(['model' => $model]);
?>